### ISSUE TITLE
Create Layout Module in Angular

### ISSUE THREAD

**Issue by dieguisherrera** [davidtorroija/angular-marketplace#19]
As a developer I want a layout module to only contains navigation components and routes in the main page after login
So that we can have a well organized scheme according the bussines logic

**Comment by davidtorroija** [comment]
@nrodriguez11 @jeannsensei @dieguisherrera  I'm not quite sure about this approach based on the Jean document

app module
- core module
  guards
  models
  pipes
  services
- shared module
  components
  directives
  pipes
  models
- auth module
  components
  models
  pages
  services
- products module
  components
  models
  pages
  services
  
  any thoughts?

**Comment by dieguisherrera** [comment]
> @nrodriguez11 @jeannsensei @dieguisherrera I'm not quite sure about this approach based on the Jean document
> 
> app module
> 
> * core module
>   guards
>   models
>   pipes
>   services
> * shared module
>   components
>   directives
>   pipes
>   models
> * auth module
>   components
>   models
>   pages
>   services
> * products module
>   components
>   models
>   pages
>   services
>   any thoughts?

Yeap, yesterday after you went, we start discus in how to separate core logic from login logic. I propose have a 3th layoutModule that will be lazy loaded only after the user login to the app, so it's not needed anymore to bootstrap all components on the core. @jeannsensei and @nrodriguez11 agree and ask me to prepare a PR with this approach

**Comment by jeannsensei** [comment]
> @nrodriguez11 @jeannsensei @dieguisherrera I'm not quite sure about this approach based on the Jean document
> 
> app module
> 
> * core module
>   guards
>   models
>   pipes
>   services
> * shared module
>   components
>   directives
>   pipes
>   models
> * auth module
>   components
>   models
>   pages
>   services
> * products module
>   components
>   models
>   pages
>   services
>   any thoughts?


@davidtorroija Hi David
We talked about the layout module after I did that. 
Diego showed us in the meeting a good way of setting up the layout of the site.
Sorry, I had to elaborate it further.

From what we we're seeing yesterday, in Angular projects they follow this folder structure inside app.module, we're basing on this article https://medium.com/@shijin_nath/angular-right-file-structure-and-best-practices-that-help-to-scale-2020-52ce8d967df5

core module (required)
- guards
- models
- pipes
- services

shared module (required)
- components
- directives
- pipes
- models

Then, all the following modules should have theses folders:
- components
- models
- pages
- services

**Comment by davidtorroija** [comment]
So this "layout" component will wrap the other modules? @dieguisherrera @jeannsensei @nrodriguez11 It will be awesome if somebody provides a simple draw to clarify this
