### ISSUE TITLE
Which libraries are we going to use on the client?

### ISSUE THREAD

**Issue by jeannsensei** [davidtorroija/angular-marketplace#5]
As a developer I want to know which libraries are we going to use so that we can be prepared we the time for DAT comes.

From what I saw on DAT, they use the material design components for Angular: https://material.angular.io/
That would be one which I think we surely have to use.

Maybe we can ask Julio or Camilo to know some of the things that they use. What do you think? @davidtorroija

**Comment by davidtorroija** [comment]
Sounds good to me, let's do that but start with the basic libraries at the beginning

**Comment by dieguisherrera** [comment]
Creo que son básicas ademas: 
RXJS
Jasmine
esLint
Pretier

Estas últimas definiendo las reglas de formato que seguiremos

**Comment by jeannsensei** [comment]
I'm doing some research about the linting rules for Prettier, maybe we can check the configuration for ESLint later.
After I finish that (I'm modifying the README.md for the client project), I'll proceed with the installation of Angular Material and that would be all for now because RXJS, Jasmine and Karma comes preinstalled in Angular projects.

**Comment by jeannsensei** [comment]
@nrodriguez11 did the Angular Material installation. Is waiting to be merged: #17
